### PR TITLE
Removed unnecessary Meteor.isServer condition

### PR DESCRIPTION
**Pull request by vinu123**

### CODE REVIEW

**Comment by yauh** [comment]
just to clarify, I will delete this repo in the next couple of days. We use a new one to have a clean history for when the book goes into production.

**Comment by vinu123** [comment]
Cool. I am buying a copy when it becomes available. We had 1 project just like this but it was rails. i wish I knew meteor then. Would've been perfect.

Thanks Stephan

**Comment by yauh** [comment]
Why wait - you can buy it now and it even has all the content already. We are in the process of cleaning things up, but these are just tiny details we're changing at this point. Make sure to use a 40% discount with the code `jn15met` at checkout!

**Comment by vinu123** [comment]
Oh...awesome.

Thanks Stephan

*विनोद सोबले*,
Vinod Sobale,
*Front End Developer <http://www.vinodsobale.com/>*
*Skype: *vinod.sobale

On Wed, Apr 22, 2015 at 10:41 PM, Stephan Hochhaus <notifications@github.com

**Pull request closed without merging**
